---
pipeline:
  build:
    privileged: true
    image: rancher/dapper:1.11.2
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    commands:
    - dapper ci

  stage-binaries:
    image: rancher/dapper:1.11.2
    commands:
    - cp -r ./bin/storage ./package/
    - curl -sLf https://raw.githubusercontent.com/rancher/rancher/98660ada3d800f653fc1f105771b5173f9d1a019/server/bin/update-rancher-ssl > package/common/update-rancher-ssl
    - chmod +x package/common/update-rancher-ssl
    when:
      branch: master
      event: tag

  publish-image-storage-abs:
    image: plugins/docker
    dockerfile: package/abs/Dockerfile
    repo: rancher/storage-abs
    context: package/
    tag: ${DRONE_TAG}
    secrets: [docker_username, docker_password]
    when:
      branch: master
      event: tag

  publish-image-storage-ebs:
    image: plugins/docker
    dockerfile: package/ebs/Dockerfile
    repo: rancher/storage-ebs
    context: package/
    tag: ${DRONE_TAG}
    secrets: [docker_username, docker_password]
    when:
      branch: master
      event: tag

  publish-image-storage-longhorn:
    image: plugins/docker
    dockerfile: package/longhorn/Dockerfile
    repo: rancher/storage-longhorn
    context: package/
    tag: ${DRONE_TAG}
    secrets: [docker_username, docker_password]
    when:
      branch: master
      event: tag

  publish-image-storage-nfs:
    image: plugins/docker
    dockerfile: package/nfs/Dockerfile
    repo: rancher/storage-nfs
    context: package/
    tag: ${DRONE_TAG}
    secrets: [docker_username, docker_password]
    when:
      branch: master
      event: tag

  publish-image-storage-rbd:
    image: plugins/docker
    dockerfile: package/rbd/Dockerfile
    repo: rancher/storage-rbd
    context: package/
    tag: ${DRONE_TAG}
    secrets: [docker_username, docker_password]
    when:
      branch: master
      event: tag

  publish-image-storage-secrets-bridge-v2:
    image: plugins/docker
    dockerfile: package/secrets-bridge-v2/Dockerfile
    repo: rancher/storage-secrets-bridge-v2
    context: package/
    tag: ${DRONE_TAG}
    secrets: [docker_username, docker_password]
    when:
      branch: master
      event: tag

  publish-image-storage-secrets:
    image: plugins/docker
    dockerfile: package/secrets/Dockerfile
    repo: rancher/storage-secrets
    context: package/
    tag: ${DRONE_TAG}
    secrets: [docker_username, docker_password]
    when:
      branch: master
      event: tag

